{% set name = "azure-mgmt-storage" %}
{% set version = "3.1.0" %}
{% set sha256 = "854b7a9bbb8af0f70104d75110e21caf874369d776cb52600220718c7b8a5c7a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3
    - setuptools
    - pip
  run:
    - python >=3
    - azure-common >=1.1
    - msrestazure >=0.4.11

test:
  imports:
    - azure
    - azure.mgmt
    - azure.mgmt.storage
  commands:
    - python -m unittest discover -p "test_storage_*.py"

about:
  home: https://github.com/Azure/azure-sdk-for-python
  license: Apache-2.0
  summary: 'Microsoft Azure Storage Resource Management Client Library for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
