{% set name = "azure-mgmt-storage" %}
{% set version = "24.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: b1ae225ef87ada85f29c02e406140ab5895285ca64de2bcfe50b631c4818a337

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - wheel
  run:
    - python
    - msrest >=0.7.1
    - azure-mgmt-core >=1.6.0
    - typing-extensions >=4.6.0

test:
  imports:
    - azure.mgmt.storage
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-mgmt-storage
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Microsoft Azure Storage Resource Management Client Library for Python
  description: |
    This is the Microsoft Azure Storage Management Client Library for Python.
    This package has been tested with Python 3.7+.
    For a more complete view of Azure libraries, see the azure sdk python release.
  dev_url: https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/storage/azure-mgmt-storage
  doc_url: https://azure.github.io/azure-sdk-for-python/

extra:
  recipe-maintainers:
    - dhirschfeld
    - Maxyme
