travis:
  secure:
    BINSTAR_TOKEN: bKQ+dUI/oJysKyrUKhUqPwljf+7o7CK2MGJaadITYv3rzrZwJbZ3bgYxaR5Kh9MwRMMNZAcS9AYneHVmv4Zhbi1l5Q6u2yuxrx8KQnTkg5aU4TPugm7g6Lv5reDtJrNJyhj6K4OYzH+n2urgnZn4Ou6NwkQ4+PBVXy8xqS64SmEgVsZbPhaD/UKrCbVYtyDu9EGdcMEB8+4FRZhdpNjBW0jLUtLLsOuUJF2DaFn8nYKzOnofENzzLWZ8dp55LuwE67exv8r7QvQFE2GxOKv65q5jqSh5jPp5mQlewZfpVrfdP2Fy5N7rdvfz0MRw32DhgXOr3LlAII+4B43WjOTj7PW1gL5FlAa90QhANVvRP4yUVBOJVoIAo5diy0vv1A1LDFCm55WP/TybPxNuY4AMXmzA/Li82iwEw7jJUgzmAu4QmdazcNhn5ja/xAOLomr2E98MsQNSPmf8MZNAcPwRXk9CES4onScxMuPQZxEFqelGH/RsWczC6fJd8y8sjHRjUa3ldhm6zoWR5gJ2fX0yudJyRhhu49iHpGF/NW3OWWE0lXRkezWQ91qGLE229ZvbNpLCcjKGFU2UCH9DfRs2E41ekcKaVAzelcLClKjO3i1IMzM1yRKvapHDvWzEMXbaWXYk5nvLqfx7+hM6mlq3wnrmL/6JbrYkb8mEudCkRVw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
