travis:
  secure:
    BINSTAR_TOKEN: Sb30Uc0vdBF8nzHxuRjN5Syiky4p1Akt42YiWKH3CpMsoAoa+BcI6MOAtiADcMhRikyDsIb4f6dJyqCnBijlaWfXqb8WzW0s9u7aHGoV6XD1ZRoFu85PijZkKkZp7wm2TivLZ2Oxft9EhRs7UqdCN4aKkrQBuDQly4oncVMkmVObQ7Aeo2p2bwWh9SI9LyC96LhdE8TlekMZtTA90JM4++jn8LzUs6DZLwPXXNYB8O8x7WNLSG1RHNGhMMcicq5l/NIen4/A6FBax94uTFzhwg4n6NtvztUNdPy2n+4QRXjDfInHz4Vhrs5T7L22vp7iKjLwfA1aNBnSrZcknELU43ILIgbj/TocrRoku5v/R3tSKFx6E0rgDjokrdFs8Gv2bXUuiUMOVDvV/Bdh7MC0jvKGQByLha9ZfWN96+k4xZpd73gbor+708tHIa9kdaVjRXBUnueRuGyaNA7MAXHDeveiYB88vW7wnbkaG3qWQriEnMtwsLvzmcxmMsnpzhTbhkzhb6j2QXAXgBINnyrytosDpuSMWDYOKvqzxv5v057Au8yHB2PAHoaSuon+WOwkMl8hTO/tI0sJYT2lONFXaZkVU4rZFkQYvimpk2gcAhyJWNvj26/ph94KPWtXxEX/pRL/K44qFAtVFikxVEka4V5kheo/MY+0IBf5eNuiUL4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
