travis:
  secure:
    BINSTAR_TOKEN: czkmCe3ATa9FXU1HBajSNmdOTbIiVNvFm+9WuYTH0Er4T9A/9jPScUu77Gje1Kv6ajiI1Cf3OljpImJEgV9Rws+F1tDNArG+R09bOr1qKtEDRcWtAVDPdEIFKko8e5AFY7dIIcg6mIIE6TAsEiicBXlGn1fmFzA9dKggBDhAs681uoS6lTSNn6lbx9UagYuf0S0jEDKFhD7xqQ0E3S4VFK8a05Jfn5tNGkMaiPyONxmRc5MmPAHOyoXiN2Kr5BAftUeoIwTv66/185XMyipofAAORff9pMpPMD3HIB/MU2FrH46RJuN+8KyIGUi9gqn7I0t9WfYT+01jz2XEMCZD43MYzryaNAgg9/0MbsIXoYzKhHN17Tf+ypobmUst0W7+ve/SUigwJOLm82wVq56sasGaSUJQpdhy2s1h7+b39DkN3kT0ywFo+kUvFklvxr3jLA+lFkGaxqeMI8Kgivth60cZcebrbgAA1t854gAKKftFBHkPuW6hiNvgRdymaSSW2tzmR6HHeIVcnEQs2gPq1tojK4Kakt/uSvn7ZagzbKoPEVaLvM9c/aXpGQtUwraAZEOunvt8w+YV2zOvZ30cTPFUbnaDT6o0AVnidhvoosegBTfQpZfmB8cCuynXgjZ7LLQ4rikZG5TGV5p47OH9L+H05RsGvR2XZAqhMrCfoQU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
